# Generated by Django 5.1.4 on 2024-12-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Front_End_Skill',
            new_name='Backend_Skill',
        ),
        migrations.RenameModel(
            old_name='Back_End_Skill',
            new_name='Frontend_Skill',
        ),
    ]
