# Generated by Django 5.1.4 on 2024-12-27 10:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
            ],
        ),
    ]
