# Generated by Django 5.1.4 on 2025-01-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_technology_project_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
